### ISSUE TITLE
Library Attachments are being read regardless of contentType

### ISSUE THREAD

**Issue by oyisre** [ccsm-cds-tools/encender#2]
The cql-execution library can only execute ELM JSON, and throws an error when given any other type (say, CQL).

It's possible for a Library to contain multiple Attachments, each representing a different data type. The library should only read ELM JSON Attachments, which we can determine by the Attachment's contentType "application/elm+json" (https://www.iana.org/assignments/media-types/application/elm+json).

**Comment by mickohanlon23** [comment]
Addressed in PR #3. Thanks for picking this up. We agree that setting Library `content.contentType` to `application/elm+json` is more accurate, and conforms to the [Executable profile of a CPG FHIR Library](http://hl7.org/fhir/uv/cpg/StructureDefinition-cpg-executablelibrary.html).

The error handling is a nice addition!
