### ISSUE TITLE
Small-scale example projects would be huge time-savers.

### ISSUE THREAD

**Issue by workcartersmith** [ccsm-cds-tools/encender#6]
Currently I can only find one repository on Github that contains the string `import { applyPlan } from 'encender';`. Having a small `examples` directory with even one example project, even if just one or two files, would be immensely helpful.

**Comment by dwwinters** [comment]
Hey @workcartersmith, that's a great suggestion.  There is a [test folder](https://github.com/ccsm-cds-tools/encender/tree/main/test) that has some simple examples:
- [Activity definitions](https://github.com/ccsm-cds-tools/encender/blob/main/test/main.test.js#L207)
- [Applicability conditions](https://github.com/ccsm-cds-tools/encender/blob/main/test/main.test.js#L331)
- [Dynamic values](https://github.com/ccsm-cds-tools/encender/blob/main/test/main.test.js#L407)

There's also a more [in-depth example](https://github.com/ccsm-cds-tools/ccsm-cds-with-tests/blob/main/apply/screening-example.js) over in [ccsm-cds-with-tests](https://github.com/ccsm-cds-tools/ccsm-cds-with-tests).  I'll make a note to call this out in the encender README file.  We also accept pull requests if you come up with any examples you think are insightful.

**Comment by workcartersmith** [comment]
My mistake - I should have been more thorough. Thank you for the reply and the addition to the readme!
